export const expense = {
    baby: require('../../assets/icons/expense/babies.png'),
    beer: require('../../assets/icons/expense/beer.png'),
    business: require('../../assets/icons/expense/business.png'),
    carMaintenance: require('../../assets/icons/expense/car-maintenance.png'),
    carWash: require('../../assets/icons/expense/car-wash.png'),
    cloth: require('../../assets/icons/expense/cloth.png'),
    coffeeCookie: require('../../assets/icons/expense/coffee-cookie.png'),
    doctor: require('../../assets/icons/expense/doctor.png'),
    education: require('../../assets/icons/expense/education.png'),
    electricityBill: require('../../assets/icons/expense/electricity-bill.png'),
    footwear: require('../../assets/icons/expense/footwear.png'),
    funeral: require('../../assets/icons/expense/funeral.png'),
    furniture: require('../../assets/icons/expense/furniture.png'),
    gambling: require('../../assets/icons/expense/gambling.png'),
    game: require('../../assets/icons/expense/game.png'),
    gas: require('../../assets/icons/expense/gas.png'),
    gift: require('../../assets/icons/expense/gift.png'),
    grocery: require('../../assets/icons/expense/grocery.png'),
    houseImprovement: require('../../assets/icons/expense/house-improvement.png'),
    insurances: require('../../assets/icons/expense/insurances.png'),
    internetBill: require('../../assets/icons/expense/internet-bill.png'),
    investment: require('../../assets/icons/expense/investment.png'),
    laundry: require('../../assets/icons/expense/laundry.png'),
    marriage: require('../../assets/icons/expense/marriage.png'),
    massage: require('../../assets/icons/expense/massage.png'),
    medical: require('../../assets/icons/expense/medical.png'),
    milk: require('../../assets/icons/expense/milk.png'),
    movie: require('../../assets/icons/expense/movie.png'),
    otherExpense: require('../../assets/icons/expense/other-expense.png'),
    parking: require('../../assets/icons/expense/parking.png'),
    pets: require('../../assets/icons/expense/pets.png'),
    phoneBill: require('../../assets/icons/expense/phone-bill.png'),
    salon: require('../../assets/icons/expense/salon.png'),
    sodas: require('../../assets/icons/expense/sodas.png'),
    tea: require('../../assets/icons/expense/tea.png'),
    televisionBill: require('../../assets/icons/expense/television-bill.png'),
    transportation: require('../../assets/icons/expense/transportation.png'),
    travel: require('../../assets/icons/expense/travel.png'),
    whiskey: require('../../assets/icons/expense/whiskey.png'),
    wine: require('../../assets/icons/expense/wine.png'),
    withdrawal: require('../../assets/icons/expense/withdrawal.png'),
}

export const income = {
    award: require('../../assets/icons/income/award.png'),
    gift: require('../../assets/icons/income/gift.png'),
    otherIncome: require('../../assets/icons/income/other-income.png'),
    salary: require('../../assets/icons/income/salary.png'),
}
